### ISSUE TITLE
Yolo doesn't start on first start

### ISSUE THREAD

**Issue by jshridha** [lawtancool/shinobi-docker-yolo#3]
@lawtancool Thanks for all of the wonderful work! I was planning on dockerizing the yolo plugin, and you saved me a bunch of work!

I'm currently having an issue where yolo does not start properly when it first starts up because the shinobi-core container starts up too slowly and the yolo pugin does not have connection to it immediately. Is there a way to add a retry to the connection or to restart the docker on error? I haven't found a way to pass this error up to pm2-runtime, so just adding in a restart hasn't worked yet.

This would also be good to implement in case shinobi-core momentarily crashes and starts back up. Currently yolo would not reconnnect if core crashes.

Thanks again and let me know how I can help.

**Comment by lawtancool** [comment]
I think the problem is that the Shinobi YOLO plugin code itself doesn't restart, attempt reconnection, or properly send an error signal to pm2-runtime on failure. This is more of an issue with the base Shinobi code than this Docker container. I'll contact the original author of Shinobi to see if they can add a proper error signal to the plugin code which would cause the whole Docker container to restart.

**Comment by jshridha** [comment]
@lawtancool That's what I was thinking also. Thanks for reaching out to the Shinobi team. I'll follow the issue on their gitlab.

**Comment by lawtancool** [comment]
@jshridha Just to let you know, the latest `dev` branch of Shinobi should now try reconnecting to the core on failure. https://gitlab.com/Shinobi-Systems/Shinobi/commit/ada584b289c62efe6860719b85a52eb2049c83ff
